### ISSUE TITLE
Option to choose save folder/category for some screenshots.

### ISSUE THREAD

**Issue by gety9** [cvzi/ScreenshotTile#322]
Thank you for amazing app!

My workflow (as probably many of other users) involves taking screenshots for different categories, say:

-, default (mix of screenshots of medium importance, most goes here)
-, work (important screenshots, can't loose)
-, hobby1 (cooking)
-, hobby2 (programming)
etc

Now they all go in same folder and at the end i have mess i have to navigate through and recategorize later.

I suggest following workflow:
1, by default all screenshots go to default folder
2, but after area of screenshot is selected to have additional button wich will trigger saving screenshot to custom category (or at least ability to save with custom name)

**Comment by gety9** [comment]
i see you have https://github.com/cvzi/ScreenshotTile/issues/147, but i don't figure out how to use it.

**Comment by cvzi** [comment]
I'll think about this and how it could be done. 
Probably the simplest solution would be to show a button in the notification to move the file to a different folder.

> i see you have #147, but i don't figure out how to use it.

For the renaming from the notification, you need to go into the settings and find the "Notification buttons" settings. There you need to enable the "Rename" option (and disable another option, since only three are allowed at the same time).

**Comment by cvzi** [comment]
Now there is an option to move the image after the screenshot was taken:

You need to open the app and scroll down and tap the button "Subsequent actions".
There you need to select "Open in Details view". 
![Screenshot](https://user-images.githubusercontent.com/8470684/236569514-9ce703fe-ca3b-4c49-aa25-54c5b6c362fa.png)
After you take a screenshot, the app will open the screenshot with options to move and rename the file.
